export enum TypesOfActions {
	AUTH_SIGNIN = 'AUTH_SIGNIN',
	AUTH_SIGNUP = 'AUTH_SIGNUP',
	AUTH_SIGNOUT = 'AUTH_SIGNOUT',
	AUTH_FORGOTPW = 'AUTH_FORGOTPW',
	AUTH_CHANGE_CHOICE = 'AUTH_CHANGE_CHOICE',
	AUTH_ERROR_SIGNIN = 'AUTH_ERROR_SIGN_IN',
	AUTH_ERROR_SIGNUP = 'AUTH_ERROR_SIGN_UP',
	AUTH_ERROR_SIGNOUT = 'AUTH_ERROR_SIGNOUT',
	AUTH_ERROR_FORGOTPW = 'AUTH_ERROR_FORGOTPW',

	CURRENT_USER_GLOBAL_ERRORS = 'CURRENT_USER_GLOBAL_ERRORS',
	CURRENT_USER_CHANGE_LOCATION = 'CURRENT_USER_CHANGE_LOCATION',

	FILE_UPLOAD_PROGRESS = 'FILE_UPLOAD_PROGRESS',
	SHOW_LOADER = 'SHOW_LOADER',
	FILE_UPLOAD_PROGRESS_POSTS = 'FILE_UPLOAD_PROGRESS_POSTS',
	FILE_UPLOAD_PROGRESS_FAQ = 'FILE_UPLOAD_PROGRESS_FAQ',
	FAQ_IMG_ARR = 'FAQ_IMG_ARR',
	APP_DATA_LOADED_USERS = 'APP_DATA_LOADED_USERS',

	CURRENT_USER_ADD_IMG = 'CURRENT_USER_ADD_IMG',

	CURRENT_USER_ITEM_SET = 'CURRENT_USER_ITEM_SET',
	CURRENT_USER_ITEM_IMG_ADD = 'CURRENT_USER_ITEM_IMG_ADD',
	CURRENT_USER_ITEM_IMG_EDIT = 'CURRENT_USER_ITEM_IMG_EDIT',
	CURRENT_USER_ITEM_IMG_DELETE = 'CURRENT_USER_ITEM_IMG_DELETE',
	CURRENT_USER_ITEM_DONE = 'CURRENT_USER_ITEM_DONE',

	CURRENT_USER_GROUP_SET = 'CURRENT_USER_GROUP_SET',
	CURRENT_USER_GROUP_IMG_ADD = 'CURRENT_USER_GROUP_IMG_ADD',
	CURRENT_USER_GROUP_IMG_EDIT = 'CURRENT_USER_GROUP_IMG_EDIT',
	CURRENT_USER_GROUP_IMG_DELETE = 'CURRENT_USER_GROUP_IMG_DELETE',

	CURRENT_USER_DONATIONS_IMG_EDIT = 'CURRENT_USER_DONATIONS_IMG_EDIT',
	CURRENT_USER_DONATIONS_SET_ON_NAV_AWAY = 'CURRENT_USER_DONATIONS_SET_ON_NAV_AWAY',
	CURRENT_USER_DON_IMG_ADD = 'CURRENT_USER_DON_IMG_ADD',
	CURRENT_USER_DON_IMG_DELETE = 'CURRENT_USER_DON_IMG_DELETE',

	CURRENT_GROUP_ITEM_SET = 'CURRENT_GROUP_ITEM_SET',
	CURRENT_GROUP_ITEM_IMG_ADD = 'CURRENT_GROUP_ITEM_IMG_ADD',
	CURRENT_GROUP_ITEM_IMG_EDIT = 'CURRENT_GROUP_ITEM_IMG_EDIT',
	CURRENT_GROUP_ITEM_IMG_DELETE = 'CURRENT_GROUP_ITEM_IMG_DELETE',

	CURRENT_USER_EVENT_SET = 'CURRENT_USER_EVENT_SET',
	CURRENT_USER_EVENT_SET_LOC = 'CURRENT_USER_EVENT_SET_LOC',
	CURRENT_USER_EVENT_IMG_ADD = 'CURRENT_USER_EVENT_IMG_ADD',
	CURRENT_USER_EVENT_IMG_EDIT = 'CURRENT_USER_EVENT_IMG_EDIT',

	CURRENT_USER_NOTIFS = 'CURRENT_USER_NOTIFS'
}
