import React, { Component } from 'react';
import { BookImgs } from './images/0ExportBookImgs';

export class Book18 extends Component {
	render() {
		return (
			<div className='calibre' id='calibre_link-0'>
				<p className='block_' lang='af'>
					<img src={BookImgs.dagboek} alt='broken' />
					<img src={BookImgs.title} alt='broken' className='calibre2' />
				</p>
				<p className='block_2'>
					<span className='text_'> </span>
					<span className='text_1'>LOCKDOWN TUIS SKOOL...</span>
				</p>
				<h1 className='block_' id='calibre_link-14'>
					&nbsp;
				</h1>
				<h1 className='block_3' id='calibre_link-15'>
					<span className='text_2'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Goed</span>
					<span className='text_3'> </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>gaan</span>
					<span className='text_3'> </span>
					<span className='text_3'>eerlik</span>
					<span className='text_3'> </span>
					<span className='text_3'>wees</span>
					<span className='text_3'> die </span>
					<span className='text_3'>skole</span>
					<span className='text_3'> se </span>
					<span className='text_3'>sisteem</span>
					<span className='text_3'> is so </span>
					<span className='text_3'>opgemors</span>
					<span className='text_3'> in my </span>
					<span className='text_3'>opinie</span>
					<span className='text_3'> </span>
					<span className='text_3'>dat</span>
					<span className='text_3'> </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>regtig</span>
					<span className='text_3'> </span>
					<span className='text_3'>rillings</span>
					<span className='text_3'> </span>
					<span className='text_3'>kry</span>
					<span className='text_3'> as </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> net </span>
					<span className='text_3'>daaraan</span>
					<span className='text_3'> dink </span>
					<span className='text_3'>dat</span>
					<span className='text_3'> </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>Karliq</span>
					<span className='text_3'> </span>
					<span className='text_3'>moet</span>
					<span className='text_3'> </span>
					<span className='text_3'>skool</span>
					<span className='text_3'> toe </span>
					<span className='text_3'>stuur</span>
					<span className='text_3'> </span>
					<span className='text_3'>oor</span>
					<span className='text_3'> 'n </span>
					<span className='text_3'>paar</span>
					<span className='text_3'> </span>
					<span className='text_3'>jaar</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Glo</span>
					<span className='text_3'> my </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>weet</span>
					<span className='text_3'> hoe </span>
					<span className='text_3'>dit</span>
					<span className='text_3'> </span>
					<span className='text_3'>voel</span>
					<span className='text_3'> </span>
					<span className='text_3'>om</span>
					<span className='text_3'> </span>
					<span className='text_3'>geboelie</span>
					<span className='text_3'> </span>
					<span className='text_3'>te</span>
					<span className='text_3'> word tot 'n punt </span>
					<span className='text_3'>waar</span>
					<span className='text_3'> 'n </span>
					<span className='text_3'>gloeiende</span>
					<span className='text_3'> warm&nbsp; </span>
					<span className='text_3'>yster</span>
					<span className='text_3'> teen my </span>
					<span className='text_3'>bo</span>
					<span className='text_3'> been </span>
					<span className='text_3'>gedruk</span>
					<span className='text_3'> was </span>
					<span className='text_3'>deur</span>
					<span className='text_3'> 'n </span>
					<span className='text_3'>skoolseun</span>
					<span className='text_3'> in my </span>
					<span className='text_3'>klas</span>
					<span className='text_3'> op die </span>
					<span className='text_3'>ouderdom</span>
					<span className='text_3'> van 13.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>weier</span>
					<span className='text_3'> </span>
					<span className='text_3'>dat</span>
					<span className='text_3'> my kind 'n </span>
					<span className='text_3'>produk</span>
					<span className='text_3'> word van die </span>
					<span className='text_3'>sisteem</span>
					<span className='text_3'>.&nbsp; So die </span>
					<span className='text_3'>enigste</span>
					<span className='text_3'> </span>
					<span className='text_3'>ander</span>
					<span className='text_3'> </span>
					<span className='text_3'>opsie</span>
					<span className='text_3'> is </span>
					<span className='text_3'>om</span>
					<span className='text_3'> </span>
					<span className='text_3'>dan</span>
					<span className='text_3'> </span>
					<span className='text_3'>om</span>
					<span className='text_3'> </span>
					<span className='text_3'>haar</span>
					<span className='text_3'> in </span>
					<span className='text_3'>te</span>
					<span className='text_3'> </span>
					<span className='text_3'>skryf</span>
					<span className='text_3'> </span>
					<span className='text_3'>vir</span>
					<span className='text_3'> </span>
					<span className='text_3'>tuis</span>
					<span className='text_3'> </span>
					<span className='text_3'>skool</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Soos</span>
					<span className='text_3'> </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>deur</span>
					<span className='text_3'> die </span>
					<span className='text_3'>navorsing</span>
					<span className='text_3'> </span>
					<span className='text_3'>werk</span>
					<span className='text_3'> </span>
					<span className='text_3'>raak</span>
					<span className='text_3'> </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>opgewonde</span>
					<span className='text_3'>. </span>
					<span className='text_3'>Ons</span>
					<span className='text_3'> </span>
					<span className='text_3'>besluit</span>
					<span className='text_3'> toe </span>
					<span className='text_3'>om</span>
					<span className='text_3'> </span>
					<span className='text_3'>vir</span>
					<span className='text_3'> </span>
					<span className='text_3'>Karliq</span>
					<span className='text_3'> </span>
					<span className='text_3'>nou</span>
					<span className='text_3'> al </span>
					<span className='text_3'>uit</span>
					<span className='text_3'> die </span>
					<span className='text_3'>sisteem</span>
					<span className='text_3'> </span>
					<span className='text_3'>te</span>
					<span className='text_3'> </span>
					<span className='text_3'>haal</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
						Die geld{' '}
					</span>
					<span className='text_3'>wat</span>
					<span className='text_3'> </span>
					<span className='text_3'>ons</span>
					<span className='text_3'> </span>
					<span className='text_3'>sou</span>
					<span className='text_3'> </span>
					<span className='text_3'>betaal</span>
					<span className='text_3'> </span>
					<span className='text_3'>vir</span>
					<span className='text_3'> </span>
					<span className='text_3'>haar</span>
					<span className='text_3'> </span>
					<span className='text_3'>kleuterskool</span>
					<span className='text_3'> het </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> en Lukas </span>
					<span className='text_3'>besluit</span>
					<span className='text_3'> </span>
					<span className='text_3'>om</span>
					<span className='text_3'> </span>
					<span className='text_3'>iemand</span>
					<span className='text_3'> in </span>
					<span className='text_3'>diens</span>
					<span className='text_3'> </span>
					<span className='text_3'>te</span>
					<span className='text_3'> </span>
					<span className='text_3'>neem</span>
					<span className='text_3'> </span>
					<span className='text_3'>halfdag</span>
					<span className='text_3'> </span>
					<span className='text_3'>sodat</span>
					<span className='text_3'> </span>
					<span className='text_3'>sy</span>
					<span className='text_3'> </span>
					<span className='text_3'>kan</span>
					<span className='text_3'> </span>
					<span className='text_3'>Karliq</span>
					<span className='text_3'> leer by die </span>
					<span className='text_3'>huis</span>
					<span className='text_3'> </span>
					<span className='text_3'>terwyl</span>
					<span className='text_3'> </span>
					<span className='text_3'>sy</span>
					<span className='text_3'> </span>
					<span className='text_3'>ook</span>
					<span className='text_3'> 'n </span>
					<span className='text_3'>uur</span>
					<span className='text_3'> </span>
					<span className='text_3'>aan</span>
					<span className='text_3'> die </span>
					<span className='text_3'>huis</span>
					<span className='text_3'> </span>
					<span className='text_3'>spandeer</span>
					<span className='text_3'> </span>
					<span className='text_3'>elke</span>
					<span className='text_3'> dag </span>
					<span className='text_3'>om</span>
					<span className='text_3'> </span>
					<span className='text_3'>skoon</span>
					<span className='text_3'> </span>
					<span className='text_3'>te</span>
					<span className='text_3'> </span>
					<span className='text_3'>maak</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
						Die plan{' '}
					</span>
					<span className='text_3'>klink</span>
					<span className='text_3'> </span>
					<span className='text_3'>goed</span>
					<span className='text_3'> en </span>
					<span className='text_3'>ons</span>
					<span className='text_3'> </span>
					<span className='text_3'>stel</span>
					<span className='text_3'> die </span>
					<span className='text_3'>kontrak</span>
					<span className='text_3'> op en </span>
					<span className='text_3'>verduidelik</span>
					<span className='text_3'> </span>
					<span className='text_3'>aan</span>
					<span className='text_3'> </span>
					<span className='text_3'>Phumeza</span>
					<span className='text_3'> </span>
					<span className='text_3'>ons</span>
					<span className='text_3'> </span>
					<span className='text_3'>nuwe</span>
					<span className='text_3'> </span>
					<span className='text_3'>hulp</span>
					<span className='text_3'> </span>
					<span className='text_3'>dat</span>
					<span className='text_3'> </span>
					<span className='text_3'>sy</span>
					<span className='text_3'> </span>
					<span className='text_3'>elke</span>
					<span className='text_3'> dag </span>
					<span className='text_3'>tussen</span>
					<span className='text_3'> 3 en 4 </span>
					<span className='text_3'>dan</span>
					<span className='text_3'> </span>
					<span className='text_3'>kan</span>
					<span className='text_3'> 'n </span>
					<span className='text_3'>kursus</span>
					<span className='text_3'> </span>
					<span className='text_3'>doen</span>
					<span className='text_3'> </span>
					<span className='text_3'>om</span>
					<span className='text_3'> </span>
					<span className='text_3'>rekenaar</span>
					<span className='text_3'> </span>
					<span className='text_3'>te</span>
					<span className='text_3'> leer </span>
					<span className='text_3'>verstaan</span>
					<span className='text_3'> en </span>
					<span className='text_3'>dan</span>
					<span className='text_3'> </span>
					<span className='text_3'>inskryf</span>
					<span className='text_3'> </span>
					<span className='text_3'>vir</span>
					<span className='text_3'> </span>
					<span className='text_3'>kursusse</span>
					<span className='text_3'> op Shaw </span>
					<span className='text_3'>Acadamy</span>
					<span className='text_3'> </span>
					<span className='text_3'>wat</span>
					<span className='text_3'> </span>
					<span className='text_3'>ons</span>
					<span className='text_3'> </span>
					<span className='text_3'>sal</span>
					<span className='text_3'> </span>
					<span className='text_3'>betaal</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
						Steeds{' '}
					</span>
					<span className='text_3'>klink</span>
					<span className='text_3'> </span>
					<span className='text_3'>dit</span>
					<span className='text_3'> </span>
					<span className='text_3'>na</span>
					<span className='text_3'> 'n </span>
					<span className='text_3'>briljante</span>
					<span className='text_3'> plan...</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
						Tot dag{' '}
					</span>
					<span className='text_3'>een</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>besef</span>
					<span className='text_3'> </span>
					<span className='text_3'>vandag</span>
					<span className='text_3'> met 'n BANG </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>moet</span>
					<span className='text_3'> 'n </span>
					<span className='text_3'>kurikulum</span>
					<span className='text_3'> </span>
					<span className='text_3'>uitwerk</span>
					<span className='text_3'> </span>
					<span className='text_3'>vir</span>
					<span className='text_3'> </span>
					<span className='text_3'>karliq</span>
					<span className='text_3'> </span>
					<span className='text_3'>wat</span>
					<span className='text_3'> </span>
					<span className='text_3'>haar</span>
					<span className='text_3'> </span>
					<span className='text_3'>gaan</span>
					<span className='text_3'> leer en help </span>
					<span className='text_3'>groei</span>
					<span className='text_3'> en </span>
					<span className='text_3'>slegs</span>
					<span className='text_3'> </span>
					<span className='text_3'>dan</span>
					<span className='text_3'> </span>
					<span className='text_3'>kan</span>
					<span className='text_3'> </span>
					<span className='text_3'>Phumeza</span>
					<span className='text_3'> </span>
					<span className='text_3'>oorneem</span>
					<span className='text_3'> en die </span>
					<span className='text_3'>werk</span>
					<span className='text_3'> </span>
					<span className='text_3'>fisies</span>
					<span className='text_3'> met </span>
					<span className='text_3'>haar</span>
					<span className='text_3'> </span>
					<span className='text_3'>doen</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Ek</span>
					<span className='text_3'> sit en </span>
					<span className='text_3'>staar</span>
					<span className='text_3'> </span>
					<span className='text_3'>na</span>
					<span className='text_3'> my </span>
					<span className='text_3'>dagboek</span>
					<span className='text_3'> </span>
					<span className='text_3'>wat</span>
					<span className='text_3'> </span>
					<span className='text_3'>propvol</span>
					<span className='text_3'> is, </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>meen</span>
					<span className='text_3'> </span>
					<span className='text_3'>stampvol</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
						Here{' '}
					</span>
					<span className='text_3'>asb</span>
					<span className='text_3'> lei my.&nbsp; </span>
					<span className='text_3'>Ek</span>
					<span className='text_3'> bid </span>
					<span className='text_3'>sommer</span>
					<span className='text_3'> </span>
					<span className='text_3'>kliphard</span>
					<span className='text_3'>. </span>
					<span className='text_3'>Hierdie</span>
					<span className='text_3'> "plan" is </span>
					<span className='text_3'>voordelig</span>
					<span className='text_3'> </span>
					<span className='text_3'>vir</span>
					<span className='text_3'> </span>
					<span className='text_3'>Phumeza</span>
					<span className='text_3'> en </span>
					<span className='text_3'>Karliq</span>
					<span className='text_3'> en </span>
					<span className='text_3'>ons</span>
					<span className='text_3'> </span>
					<span className='text_3'>ook</span>
					<span className='text_3'>.&nbsp; Hoe </span>
					<span className='text_3'>uitvoerbaar</span>
					<span className='text_3'> is </span>
					<span className='text_3'>dit</span>
					<span className='text_3'> </span>
					<span className='text_3'>regtig</span>
					<span className='text_3'> my </span>
					<span className='text_3'>gedagtes</span>
					<span className='text_3'> </span>
					<span className='text_3'>wandel</span>
					<span className='text_3'> </span>
					<span className='text_3'>na</span>
					<span className='text_3'> Maria.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Kyk</span>
					<span className='text_3'> as </span>
					<span className='text_3'>sy</span>
					<span className='text_3'> </span>
					<span className='text_3'>kan</span>
					<span className='text_3'> 7 </span>
					<span className='text_3'>kinders</span>
					<span className='text_3'> </span>
					<span className='text_3'>grootmaak</span>
					<span className='text_3'> </span>
					<span className='text_3'>sonder</span>
					<span className='text_3'> </span>
					<span className='text_3'>tegnologie</span>
					<span className='text_3'> </span>
					<span className='text_3'>dan</span>
					<span className='text_3'> </span>
					<span className='text_3'>kan</span>
					<span className='text_3'> </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>ook</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
						Ok{' '}
					</span>
					<span className='text_3'>diep</span>
					<span className='text_3'> </span>
					<span className='text_3'>asem</span>
					<span className='text_3'>.&nbsp; </span>
					<span className='text_3'>Pinterest</span>
					<span className='text_3'> en Google is my </span>
					<span className='text_3'>beste</span>
					<span className='text_3'> </span>
					<span className='text_3'>vriende</span>
					<span className='text_3'> </span>
					<span className='text_3'>vandag</span>
					<span className='text_3'>.&nbsp; </span>
					<span className='text_3'>Daar</span>
					<span className='text_3'> is </span>
					<span className='text_3'>letterlik</span>
					<span className='text_3'> </span>
					<span className='text_3'>duisende</span>
					<span className='text_3'> </span>
					<span className='text_3'>printables</span>
					<span className='text_3'> templates en </span>
					<span className='text_3'>speel</span>
					<span className='text_3'> </span>
					<span className='text_3'>idees</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Soos</span>
					<span className='text_3'> </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>werk</span>
					<span className='text_3'> </span>
					<span className='text_3'>gly</span>
					<span className='text_3'> my </span>
					<span className='text_3'>vingers</span>
					<span className='text_3'> </span>
					<span className='text_3'>oor</span>
					<span className='text_3'> die keyboard die printer </span>
					<span className='text_3'>werk</span>
					<span className='text_3'> </span>
					<span className='text_3'>oortyd</span>
					<span className='text_3'> </span>
					<span className='text_3'>vandag</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>weet</span>
					<span className='text_3'> </span>
					<span className='text_3'>dat</span>
					<span className='text_3'> </span>
					<span className='text_3'>selfs</span>
					<span className='text_3'> in die </span>
					<span className='text_3'>idee</span>
					<span className='text_3'> God met </span>
					<span className='text_3'>ons</span>
					<span className='text_3'> </span>
					<span className='text_3'>gesin</span>
					<span className='text_3'> is en </span>
					<span className='text_3'>dat</span>
					<span className='text_3'> </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> die </span>
					<span className='text_3'>beste</span>
					<span className='text_3'> </span>
					<span className='text_3'>besluit</span>
					<span className='text_3'> </span>
					<span className='text_3'>gemaak</span>
					<span className='text_3'> het </span>
					<span className='text_3'>vir</span>
					<span className='text_3'> </span>
					<span className='text_3'>Karliq</span>
					<span className='text_3'> </span>
					<span className='text_3'>wat</span>
					<span className='text_3'> </span>
					<span className='text_3'>ek</span>
					<span className='text_3'> </span>
					<span className='text_3'>kon</span>
					<span className='text_3'>.&nbsp; </span>
					<span className='text_3'>Ek</span>
					<span className='text_3'> het </span>
					<span className='text_3'>vrede</span>
					<span className='text_3'> in my </span>
					<span className='text_3'>hart</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Ons</span>
					<span className='text_3'> </span>
					<span className='text_3'>kinders</span>
					<span className='text_3'> is</span>
					<span className='text_3'> </span>
					<span className='text_3'>kosbaar</span>
					<span className='text_3'>.&nbsp; </span>
					<span className='text_3'>Dankie</span>
					<span className='text_3'> Here </span>
					<span className='text_3'>dat</span>
					<span className='text_3'> U my die </span>
					<span className='text_3'>voorreg</span>
					<span className='text_3'> </span>
					<span className='text_3'>geggee</span>
					<span className='text_3'> het </span>
					<span className='text_3'>om</span>
					<span className='text_3'> my kind </span>
					<span className='text_3'>te</span>
					<span className='text_3'> </span>
					<span className='text_3'>kan</span>
					<span className='text_3'> help by die </span>
					<span className='text_3'>huis</span>
					<span className='text_3'> </span>
					<span className='text_3'>om</span>
					<span className='text_3'> </span>
					<span className='text_3'>te</span>
					<span className='text_3'> leer en </span>
					<span className='text_3'>terselfde</span>
					<span className='text_3'> </span>
					<span className='text_3'>tyd</span>
					<span className='text_3'> U </span>
					<span className='text_3'>beginsels</span>
					<span className='text_3'> </span>
					<span className='text_3'>te</span>
					<span className='text_3'> leer.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Ons</span>
					<span className='text_3'> het </span>
					<span className='text_3'>besluit</span>
					<span className='text_3'> op 'n program </span>
					<span className='text_3'>wat</span>
					<span className='text_3'> </span>
					<span className='text_3'>sy</span>
					<span className='text_3'> </span>
					<span className='text_3'>volgende</span>
					<span className='text_3'> </span>
					<span className='text_3'>jaar</span>
					<span className='text_3'> </span>
					<span className='text_3'>sal</span>
					<span className='text_3'> begin leer op </span>
					<span className='text_3'>tuis</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Een</span>
					<span className='text_3'> ding is </span>
					<span className='text_3'>verseker</span>
					<span className='text_3'>, </span>
					<span className='text_3'>hierdie</span>
					<span className='text_3'> </span>
					<span className='text_3'>tuis</span>
					<span className='text_3'> </span>
					<span className='text_3'>skool</span>
					<span className='text_3'> ding </span>
					<span className='text_3'>gaan</span>
					<span className='text_3'> </span>
					<span className='text_3'>baie</span>
					<span className='text_3'> </span>
					<span className='text_3'>tyd</span>
					<span className='text_3'> en </span>
					<span className='text_3'>energie</span>
					<span className='text_3'> in </span>
					<span className='text_3'>beslag</span>
					<span className='text_3'> </span>
					<span className='text_3'>neem</span>
					<span className='text_3'> en </span>
					<span className='text_3'>beplanning</span>
					<span className='text_3'>.</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>
						<br className='calibre3' />
					</span>
					<span className='text_3'>Enige</span>
					<span className='text_3'> </span>
					<span className='text_3'>iets</span>
					<span className='text_3'> is </span>
					<span className='text_3'>moontlik</span>
					<span className='text_3'>- God is in </span>
					<span className='text_3'>beheer</span>
					<span className='text_3'>, ALTYD</span>
				</h1>
			</div>
		);
	}
}

export default Book18;
