import React, { Component } from 'react';
import { BookImgs } from './images/0ExportBookImgs';

export class Book15 extends Component {
	render() {
		return (
			<div className='calibre' id='calibre_link-0'>
				<p className='block_' lang='af'>
					<img src={BookImgs.dagboek} alt='broken' />
					<img src={BookImgs.title} alt='broken' className='calibre2' />
				</p>
				<p className='block_2'>HET JOU LONGE AL ONTPLOF?</p>
				<h1 className='block_' id='calibre_link-14'>
					&nbsp;
				</h1>
				<h1 className='block_3' id='calibre_link-15'>
					<span className='text_'>Ek</span>
					<span className='text_'> word so net </span>
					<span className='text_'>duskant</span>
					<span className='text_'> 5am </span>
					<span className='text_'>wakker</span>
					<span className='text_'>.&nbsp; </span>
					<span className='text_'>Ek</span>
					<span className='text_'> dink o </span>
					<span className='text_'>koek</span>
					<span className='text_'> </span>
					<span className='text_'>talita</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>jy</span>
					<span className='text_'> het </span>
					<span className='text_'>nou</span>
					<span className='text_'> </span>
					<span className='text_'>vir</span>
					<span className='text_'> </span>
					<span className='text_'>salomie</span>
					<span className='text_'> </span>
					<span className='text_'>gese</span>
					<span className='text_'> </span>
					<span className='text_'>dat</span>
					<span className='text_'> </span>
					<span className='text_'>jy</span>
					<span className='text_'> </span>
					<span className='text_'>wil</span>
					<span className='text_'> </span>
					<span className='text_'>gaan</span>
					<span className='text_'> </span>
					<span className='text_'>stap</span>
					<span className='text_'> </span>
					<span className='text_'>saam</span>
					<span className='text_'> </span>
					<span className='text_'>haar</span>
					<span className='text_'> en </span>
					<span className='text_'>hier</span>
					<span className='text_'> is </span>
					<span className='text_'>jy</span>
					<span className='text_'> </span>
					<span className='text_'>nou</span>
					<span className='text_'> op DIE DAG die STAP DAG het </span>
					<span className='text_'>aangebreek</span>
					<span className='text_'>.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Ek</span>
					<span className='text_'> </span>
					<span className='text_'>loer</span>
					<span className='text_'> by die </span>
					<span className='text_'>venster</span>
					<span className='text_'> </span>
					<span className='text_'>uit</span>
					<span className='text_'> en bid </span>
					<span className='text_'>woordeloos</span>
					<span className='text_'> </span>
					<span className='text_'>vir</span>
					<span className='text_'> </span>
					<span className='text_'>reen</span>
					<span className='text_'> </span>
					<span className='text_'>klip</span>
					<span className='text_'> </span>
					<span className='text_'>harde</span>
					<span className='text_'> </span>
					<span className='text_'>stort</span>
					<span className='text_'> </span>
					<span className='text_'>reen</span>
					<span className='text_'>.&nbsp; </span>
					<span className='text_'>Maar</span>
					<span className='text_'> </span>
					<span className='text_'>niks</span>
					<span className='text_'> </span>
					<span className='text_'>nie</span>
					<span className='text_'> 'n </span>
					<span className='text_'>druppel</span>
					<span className='text_'> </span>
					<span className='text_'>nie</span>
					<span className='text_'>.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Ek</span>
					<span className='text_'> </span>
					<span className='text_'>staan</span>
					<span className='text_'> op drink water en </span>
					<span className='text_'>klim</span>
					<span className='text_'> </span>
					<span className='text_'>terug</span>
					<span className='text_'> in die bed... </span>
					<span className='text_'>lukas</span>
					<span className='text_'> se alarm </span>
					<span className='text_'>gaan</span>
					<span className='text_'> </span>
					<span className='text_'>af</span>
					<span className='text_'>.&nbsp; Ok </span>
					<span className='text_'>opstaan</span>
					<span className='text_'> </span>
					<span className='text_'>tyd</span>
					<span className='text_'>.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>letterlik</span>
					<span className='text_'> het </span>
					<span className='text_'>ek</span>
					<span className='text_'> </span>
					<span className='text_'>aan</span>
					<span className='text_'> 'n </span>
					<span className='text_'>duisend</span>
					<span className='text_'> </span>
					<span className='text_'>redes</span>
					<span className='text_'> </span>
					<span className='text_'>gedink</span>
					<span className='text_'> </span>
					<span className='text_'>om</span>
					<span className='text_'> </span>
					<span className='text_'>nie</span>
					<span className='text_'> </span>
					<span className='text_'>te</span>
					<span className='text_'> </span>
					<span className='text_'>gaan</span>
					<span className='text_'> </span>
					<span className='text_'>nie</span>
					<span className='text_'>. </span>
					<span className='text_'>maar</span>
					<span className='text_'> </span>
					<span className='text_'>ek</span>
					<span className='text_'> </span>
					<span className='text_'>kan</span>
					<span className='text_'> </span>
					<span className='text_'>nie</span>
					<span className='text_'> </span>
					<span className='text_'>opkom</span>
					<span className='text_'> met </span>
					<span className='text_'>een</span>
					<span className='text_'> </span>
					<span className='text_'>geldige</span>
					<span className='text_'> </span>
					<span className='text_'>rede</span>
					<span className='text_'> </span>
					<span className='text_'>nie</span>
					<span className='text_'>.&nbsp; So </span>
					<span className='text_'>ek</span>
					<span className='text_'> </span>
					<span className='text_'>staan</span>
					<span className='text_'> op trek my </span>
					<span className='text_'>tekkies</span>
					<span className='text_'> </span>
					<span className='text_'>aan</span>
					<span className='text_'> en </span>
					<span className='text_'>ry</span>
					<span className='text_'> </span>
					<span className='text_'>na</span>
					<span className='text_'> </span>
					<span className='text_'>salomie</span>
					<span className='text_'> toe.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Ek</span>
					<span className='text_'> </span>
					<span className='text_'>parkeer</span>
					<span className='text_'> </span>
					<span className='text_'>voor</span>
					<span className='text_'> </span>
					<span className='text_'>haar</span>
					<span className='text_'> </span>
					<span className='text_'>hek</span>
					<span className='text_'>.</span>
					<span className='text_'>&nbsp; Die </span>
					<span className='text_'>uitsig</span>
					<span className='text_'> is </span>
					<span className='text_'>asemrowend</span>
					<span className='text_'> </span>
					<span className='text_'>mooi</span>
					<span className='text_'> in die </span>
					<span className='text_'>gedeelte</span>
					<span className='text_'> van </span>
					<span className='text_'>ons</span>
					<span className='text_'> </span>
					<span className='text_'>mooie</span>
					<span className='text_'> </span>
					<span className='text_'>dorpie</span>
					<span className='text_'> </span>
					<span className='text_'>gonubie</span>
					<span className='text_'>. </span>
					<span className='text_'>Ek</span>
					<span className='text_'> </span>
					<span className='text_'>staar</span>
					<span className='text_'> </span>
					<span className='text_'>uit</span>
					<span className='text_'> </span>
					<span className='text_'>oor</span>
					<span className='text_'> die </span>
					<span className='text_'>kloof</span>
					<span className='text_'> en </span>
					<span className='text_'>sien</span>
					<span className='text_'> </span>
					<span className='text_'>dan</span>
					<span className='text_'> in my </span>
					<span className='text_'>tru</span>
					<span className='text_'> </span>
					<span className='text_'>spieel</span>
					<span className='text_'> die </span>
					<span className='text_'>groot</span>
					<span className='text_'> </span>
					<span className='text_'>bos</span>
					<span className='text_'> </span>
					<span className='text_'>pers</span>
					<span className='text_'> </span>
					<span className='text_'>blommetjies</span>
					<span className='text_'> </span>
					<span className='text_'>gesoen</span>
					<span className='text_'> met </span>
					<span className='text_'>oggend</span>
					<span className='text_'> </span>
					<span className='text_'>dou</span>
					<span className='text_'>.&nbsp; Die </span>
					<span className='text_'>fotograaf</span>
					<span className='text_'> in my spring </span>
					<span className='text_'>uit</span>
					<span className='text_'> die </span>
					<span className='text_'>kar</span>
					<span className='text_'> </span>
					<span className='text_'>uit</span>
					<span className='text_'> </span>
					<span className='text_'>gryp</span>
					<span className='text_'> my </span>
					<span className='text_'>kamera</span>
					<span className='text_'> en begin </span>
					<span className='text_'>fotos</span>
					<span className='text_'> </span>
					<span className='text_'>neem</span>
					<span className='text_'>.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Salomie</span>
					<span className='text_'> en Ina </span>
					<span className='text_'>staan</span>
					<span className='text_'> </span>
					<span className='text_'>skielik</span>
					<span className='text_'> </span>
					<span className='text_'>langs</span>
					<span className='text_'> my met </span>
					<span className='text_'>een</span>
					<span className='text_'> </span>
					<span className='text_'>groot</span>
					<span className='text_'> </span>
					<span className='text_'>goue</span>
					<span className='text_'> </span>
					<span className='text_'>labardor</span>
					<span className='text_'> en 'n </span>
					<span className='text_'>elsation</span>
					<span className='text_'> </span>
					<span className='text_'>sy</span>
					<span className='text_'> gee my hunter die </span>
					<span className='text_'>staffie</span>
					<span className='text_'> se </span>
					<span className='text_'>halsband</span>
					<span className='text_'> en </span>
					<span className='text_'>ons</span>
					<span className='text_'> begin </span>
					<span className='text_'>stap</span>
					<span className='text_'>.&nbsp; </span>
					<span className='text_'>Genade</span>
					<span className='text_'> </span>
					<span className='text_'>ekt</span>
					<span className='text_'> </span>
					<span className='text_'>nooit</span>
					<span className='text_'> </span>
					<span className='text_'>geweet</span>
					<span className='text_'> </span>
					<span className='text_'>hoeveel</span>
					<span className='text_'> </span>
					<span className='text_'>krag</span>
					<span className='text_'> 'n </span>
					<span className='text_'>hond</span>
					<span className='text_'> in </span>
					<span className='text_'>hom</span>
					<span className='text_'> het </span>
					<span className='text_'>nie</span>
					<span className='text_'>.</span>
					<span className='text_'>&nbsp; </span>
					<span className='text_'>Ons</span>
					<span className='text_'> </span>
					<span className='text_'>stap</span>
					<span className='text_'> en </span>
					<span className='text_'>gesels</span>
					<span className='text_'> </span>
					<span className='text_'>bo</span>
					<span className='text_'> by die </span>
					<span className='text_'>bluegum</span>
					<span className='text_'> boom </span>
					<span className='text_'>hyg</span>
					<span className='text_'> </span>
					<span className='text_'>ek</span>
					<span className='text_'> </span>
					<span className='text_'>na</span>
					<span className='text_'> </span>
					<span className='text_'>asem</span>
					<span className='text_'> </span>
					<span className='text_'>ons</span>
					<span className='text_'> </span>
					<span className='text_'>rus</span>
					<span className='text_'> so </span>
					<span className='text_'>paar</span>
					<span className='text_'> </span>
					<span className='text_'>sekondes</span>
					<span className='text_'> </span>
					<span className='text_'>dan</span>
					<span className='text_'> </span>
					<span className='text_'>stap</span>
					<span className='text_'> </span>
					<span className='text_'>ons</span>
					<span className='text_'> </span>
					<span className='text_'>verder</span>
					<span className='text_'>.&nbsp; </span>
					<span className='text_'>deur</span>
					<span className='text_'> die dip op en op.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Teen die </span>
					<span className='text_'>tyd</span>
					<span className='text_'> </span>
					<span className='text_'>voel</span>
					<span className='text_'> </span>
					<span className='text_'>dit</span>
					<span className='text_'> of my </span>
					<span className='text_'>longe</span>
					<span className='text_'> </span>
					<span className='text_'>gaan</span>
					<span className='text_'> </span>
					<span className='text_'>ontplof</span>
					<span className='text_'>.</span>
					<span className='text_'>&nbsp; </span>
					<span className='text_'>Daar</span>
					<span className='text_'> </span>
					<span className='text_'>kom</span>
					<span className='text_'> 'n </span>
					<span className='text_'>bakkie</span>
					<span className='text_'> </span>
					<span className='text_'>verby</span>
					<span className='text_'> en </span>
					<span className='text_'>skielik</span>
					<span className='text_'> </span>
					<span className='text_'>voel</span>
					<span className='text_'> </span>
					<span className='text_'>ek</span>
					<span className='text_'> of </span>
					<span className='text_'>ek</span>
					<span className='text_'> </span>
					<span className='text_'>voor</span>
					<span className='text_'> die </span>
					<span className='text_'>bakkie</span>
					<span className='text_'> </span>
					<span className='text_'>wil</span>
					<span className='text_'> </span>
					<span className='text_'>inspring</span>
					<span className='text_'> en die man </span>
					<span className='text_'>smeek</span>
					<span className='text_'> </span>
					<span className='text_'>om</span>
					<span className='text_'> my </span>
					<span className='text_'>huistoe</span>
					<span className='text_'> </span>
					<span className='text_'>te</span>
					<span className='text_'> vat! </span>
					<span className='text_'>my</span>
					<span className='text_'> </span>
					<span className='text_'>verbeelding</span>
					<span className='text_'> </span>
					<span className='text_'>hardloop</span>
					<span className='text_'> </span>
					<span className='text_'>nog</span>
					<span className='text_'> so met my </span>
					<span className='text_'>weg</span>
					<span className='text_'> toe is </span>
					<span className='text_'>ons</span>
					<span className='text_'> by die stop </span>
					<span className='text_'>straat</span>
					<span className='text_'> en </span>
					<span className='text_'>ek</span>
					<span className='text_'> </span>
					<span className='text_'>besef</span>
					<span className='text_'> </span>
					<span className='text_'>ons</span>
					<span className='text_'> is </span>
					<span className='text_'>amper</span>
					<span className='text_'> </span>
					<span className='text_'>klaar</span>
					<span className='text_'> </span>
					<span className='text_'>gestap</span>
					<span className='text_'>.&nbsp; </span>
					<span className='text_'>my</span>
					<span className='text_'> hart </span>
					<span className='text_'>bons</span>
					<span className='text_'> </span>
					<span className='text_'>skielik</span>
					<span className='text_'> van </span>
					<span className='text_'>opgewondenheid</span>
					<span className='text_'>.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Ek</span>
					<span className='text_'> het my </span>
					<span className='text_'>eerste</span>
					<span className='text_'> </span>
					<span className='text_'>mikpunt</span>
					<span className='text_'> </span>
					<span className='text_'>behaal</span>
					<span className='text_'> </span>
					<span className='text_'>vandag</span>
					<span className='text_'>.</span>
					<span className='text_'>&nbsp; </span>
					<span className='text_'>Dankie</span>
					<span className='text_'> Jesus </span>
					<span className='text_'>vir</span>
					<span className='text_'> </span>
					<span className='text_'>goeie</span>
					<span className='text_'> </span>
					<span className='text_'>vriende</span>
					<span className='text_'> en </span>
					<span className='text_'>dat</span>
					<span className='text_'> </span>
					<span className='text_'>ek</span>
					<span className='text_'> </span>
					<span className='text_'>normale</span>
					<span className='text_'> </span>
					<span className='text_'>voete</span>
					<span className='text_'> en </span>
					<span className='text_'>bene</span>
					<span className='text_'> het </span>
					<span className='text_'>dankie</span>
					<span className='text_'> </span>
					<span className='text_'>dat</span>
					<span className='text_'> </span>
					<span className='text_'>ek</span>
					<span className='text_'> </span>
					<span className='text_'>nooit</span>
					<span className='text_'> </span>
					<span className='text_'>weer</span>
					<span className='text_'> so </span>
					<span className='text_'>onfiks</span>
					<span className='text_'> </span>
					<span className='text_'>sal</span>
					<span className='text_'> </span>
					<span className='text_'>wees</span>
					<span className='text_'> </span>
					<span className='text_'>soos</span>
					<span className='text_'> </span>
					<span className='text_'>vandag</span>
					<span className='text_'> </span>
					<span className='text_'>nie</span>
					<span className='text_'>.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Ek</span>
					<span className='text_'> </span>
					<span className='text_'>groet</span>
					<span className='text_'> my </span>
					<span className='text_'>vriendin</span>
					<span className='text_'> en </span>
					<span className='text_'>kom</span>
					<span className='text_'> </span>
					<span className='text_'>huis</span>
					<span className='text_'> toe. </span>
					<span className='text_'>Ek</span>
					<span className='text_'> </span>
					<span className='text_'>stap</span>
					<span className='text_'> in en wonder of die </span>
					<span className='text_'>stap</span>
					<span className='text_'> </span>
					<span className='text_'>besigheid</span>
					<span className='text_'> </span>
					<span className='text_'>gaan</span>
					<span className='text_'> </span>
					<span className='text_'>werk</span>
					<span className='text_'>. </span>
					<span className='text_'>ons</span>
					<span className='text_'> het </span>
					<span className='text_'>vandag</span>
					<span className='text_'> 20 minute </span>
					<span className='text_'>gestap</span>
					<span className='text_'>.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Skielik</span>
					<span className='text_'> beep my </span>
					<span className='text_'>foon</span>
					<span className='text_'> in my</span>
					<span className='text_'>&nbsp; hand</span>
					<span className='text_'>.&nbsp; </span>
					<span className='text_'>Ek</span>
					<span className='text_'> </span>
					<span className='text_'>maak</span>
					<span className='text_'> </span>
					<span className='text_'>dit</span>
					<span className='text_'> </span>
					<span className='text_'>oop</span>
					<span className='text_'> </span>
					<span className='text_'>dis</span>
					<span className='text_'> 'n </span>
					<span className='text_'>boodskap</span>
					<span className='text_'> van 'n </span>
					<span className='text_'>boeremeisie</span>
					<span className='text_'>.</span>
					<span className='text_'>&nbsp; </span>
					<span className='text_'>Ek</span>
					<span className='text_'> sit en </span>
					<span className='text_'>staar</span>
					<span className='text_'> </span>
					<span className='text_'>na</span>
					<span className='text_'> die </span>
					<span className='text_'>sneeuflokkie</span>
					<span className='text_'> en </span>
					<span className='text_'>skielik</span>
					<span className='text_'> </span>
					<span className='text_'>sien</span>
					<span className='text_'> </span>
					<span className='text_'>ek</span>
					<span className='text_'> die </span>
					<span className='text_'>ongelooflike</span>
					<span className='text_'> </span>
					<span className='text_'>ooreenkoms</span>
					<span className='text_'> in </span>
					<span className='text_'>vorm</span>
					<span className='text_'> </span>
					<span className='text_'>tussen</span>
					<span className='text_'> die </span>
					<span className='text_'>sneeu</span>
					<span className='text_'> </span>
					<span className='text_'>vlokkie</span>
					<span className='text_'> en die </span>
					<span className='text_'>blommetjie</span>
					<span className='text_'>.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Bevestiging</span>
					<span className='text_'> </span>
					<span className='text_'>dat</span>
					<span className='text_'> </span>
					<span className='text_'>ek</span>
					<span className='text_'> en </span>
					<span className='text_'>jy</span>
					<span className='text_'> </span>
					<span className='text_'>gekies</span>
					<span className='text_'> is </span>
					<span className='text_'>om</span>
					<span className='text_'> </span>
					<span className='text_'>gesond</span>
					<span className='text_'> </span>
					<span className='text_'>gelukkig</span>
					<span className='text_'> </span>
					<span className='text_'>te</span>
					<span className='text_'> </span>
					<span className='text_'>lewe</span>
					<span className='text_'> </span>
					<span className='text_'>maar</span>
					<span className='text_'> </span>
					<span className='text_'>dis</span>
					<span className='text_'> die </span>
					<span className='text_'>keuses</span>
					<span className='text_'> </span>
					<span className='text_'>wat</span>
					<span className='text_'> </span>
					<span className='text_'>ons</span>
					<span className='text_'> </span>
					<span className='text_'>maak</span>
					<span className='text_'> </span>
					<span className='text_'>wat</span>
					<span className='text_'> </span>
					<span className='text_'>jou</span>
					<span className='text_'> </span>
					<span className='text_'>lewe</span>
					<span className='text_'> </span>
					<span className='text_'>stuur</span>
					<span className='text_'> </span>
					<span className='text_'>na</span>
					<span className='text_'> of Jesus of die </span>
					<span className='text_'>dood</span>
					<span className='text_'>.</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Ek</span>
					<span className='text_'> </span>
					<span className='text_'>kies</span>
					<span className='text_'> Jesus.</span>
					<span className='text_'> </span>
					<span className='text_'>Wat</span>
					<span className='text_'> </span>
					<span className='text_'>kies</span>
					<span className='text_'> </span>
					<span className='text_'>jy</span>
					<span className='text_'> </span>
					<span className='text_'>vanoggend</span>
					<span className='text_'>?</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Kaalvoet</span>
					<span className='text_'> </span>
					<span className='text_'>liefde</span>
					<span className='text_'> </span>
					<span className='text_'>Boeremeisie</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>Talita</span>
					<span className='text_'>
						<br className='calibre3' />
					</span>
					<span className='text_'>
						<br className='calibre3' />
						Ps"{' '}
					</span>
					<span className='text_'>Dankie</span>
					<span className='text_'> Julia Ann </span>
					<span className='text_'>Rossow</span>
					<span className='text_'> </span>
					<span className='text_'>vir</span>
					<span className='text_'> die </span>
					<span className='text_'>lekker</span>
					<span className='text_'> </span>
					<span className='text_'>gesels</span>
					<span className='text_'> </span>
					<span className='text_'>vanoggend</span>
					<span className='text_'>!</span>
				</h1>
			</div>
		);
	}
}

export default Book15;
