export enum TypesOfActions {
	AUTH_SIGNIN = 'AUTH_SIGNIN',
	AUTH_SIGNUP = 'AUTH_SIGNUP',
	AUTH_SIGNOUT = 'AUTH_SIGNOUT',
	AUTH_FORGOTPW = 'AUTH_FORGOTPW',
	AUTH_ERROR_SIGNIN = 'AUTH_ERROR_SIGN_IN',
	AUTH_ERROR_SIGNUP = 'AUTH_ERROR_SIGN_UP',
	AUTH_ERROR_SIGNOUT = 'AUTH_ERROR_SIGNOUT',
	AUTH_ERROR_FORGOTPW = 'AUTH_ERROR_FORGOTPW',
	AUTH_CHANGE_CHOICE = 'AUTH_CHANGE_CHOICE',

	CURRENT_USER_GLOBAL_ERRORS = 'CURRENT_USER_GLOBAL_ERRORS',
	APP_DATA_LOADED = 'APP_DATA_LOADED',
	FILE_UPLOAD_PROGRESS = 'FILE_UPLOAD_PROGRESS',

	CURRENT_USER_CHANGE_LOCATION = 'CURRENT_USER_CHANGE_LOCATION',
	CURRENT_USER_CHANGE_LANG = 'CURRENT_USER_CHANGE_LANG',
	CURRENT_USER_PROFILE_EDIT = 'CURRENT_USER_PROFILE_EDIT',
	CURRENT_USER_SEND_MSG_TO_OWNER = 'CURRENT_USER_SEND_MSG_TO_OWNER',

	OWNER_PROFILE_IMG_ADD = 'OWNER_PROFILE_IMG_ADD',
	OWNER_PROFILE_ADD_WORKDAYS = 'OWNER_PROFILE_ADD_WORKDAYS',
	OWNER_PROFILE_ADD_HOURS = 'OWNER_PROFILE_ADD_HOURS',
	OWNER_PROFILE_ADD_OFF_HOURS = 'OWNER_PROFILE_ADD_OFF_HOURS'
}
