import { i_BaseInterface_User } from "../../../models/001UserModels";

export const HelperCreateUser = (userData: i_BaseInterface_User, sessions?: any) => {
  var returnUser: i_BaseInterface_User = FakeUser;

  returnUser = {
    id: userData.id,
    name: userData.name ? userData.name : "",
    email: userData.email ? userData.email : "",
    connectp: userData.connectp ? userData.connectp : "",
    location: userData.location,
    lang: userData.lang,
    msgHistory: userData.msgHistory !== undefined ? userData.msgHistory : {},
    sessions: sessions ? sessions : {}
  };

  return returnUser;
};

export const HelperCreateOwner = (userData: any) => {
  var returnUser: any = FakeUser;
  // console.log( 'userData', userData.sessionsBooked)

  returnUser = {
    name: userData.name ? userData.name : "",
    id: userData.id,
    avatar: userData.avatar,
    email: userData.email ? userData.email : "",
    connectp: userData.connectp ? userData.connectp : "",
    location: userData.location,
    lang: userData.lang,
    workData: {
      daysOfwork: userData?.workData !== undefined ? userData?.workData?.daysOfwork : [],
      hoursOfwork: userData?.workData !== undefined ? userData?.workData?.hoursOfwork : [],
      hoursOfNonWork: userData?.workData !== undefined ? userData?.workData?.hoursOfNonWork : []
    },
    msgHistory: userData.msgHistory !== undefined ? userData.msgHistory : {},
    sessionsBooked: userData.sessionsBooked ? userData.sessionsBooked : {}
  };

  return returnUser;
};

export const HelperCreateUserKeepOld = (userData: i_BaseInterface_User, sessions?: any) => {
  var returnUser: i_BaseInterface_User = FakeUser;
  returnUser = {
    id: userData.id,
    name: userData.name ? userData.name : "",
    location: userData.location,
    email: userData.email ? userData.email : "",
    connectp: userData.connectp ? userData.connectp : "",
    lang: userData.lang,
    msgHistory: userData.msgHistory !== undefined ? userData.msgHistory : {},
    sessions: sessions ? sessions : {}
  };

  return returnUser;
};

const FakeUser = {
  id: "",
  name: "",
  email: "",
  connectp: "",
  location: {
    address: {
      district: "",
      houseNumber: "",
      street: "",
      city: "",
      state: "",
      postalCode: "",
      country: "",
      county: "",
      label: ""
    },

    locationId: "",
    locationType: "",

    coords: {
      lat: 0,
      long: 0
    }
  },
  lang: "en",
  msgHistory: {},
  sessions: {}
};

export const FakeYear = {
  0: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  1: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  2: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  3: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  4: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  5: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  6: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  7: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  8: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  9: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  10: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  },
  11: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
    26: [],
    27: [],
    28: [],
    29: [],
    30: [],
    31: []
  }
};
